###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: proyect-memcached

    mysql:
      image: mysql:8.0
      container_name: proyect-mysql
      #working_dir: /application
     # volumes:
       # - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
     # ports:
       # - "8102:3306"

    webserver:
      image: nginx:alpine
      container_name: proyect-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8100:80"
      links: 
        - mysql
        - php-fpm

    php-fpm:
      build: phpdocker/php-fpm
      container_name: proyect-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

